// import type { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "User Post",
//   description: "Generated by create next app",
// };

export default function UserPost() {
  return (
    <div>User Post</div>
  )
}
