import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Notification from "@/components/Notification";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jobseeker User List",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative px-64">
        <Notification  />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
